### DISCUSSION TITLE
Is there a way to maintain two backends?

### DISCUSSION THREAD

**Discussion by Kamish-69** [HyDE-Project/HyDE#463] [Q&A]
I want two shortcuts, one should open the wallpaper selector displaying only the .png files, and another should open it while displaying only .mp4 files from another directory? maybe if we could set two backends in ~/.config/hyde/config.toml and define different options for both?

Thanks

**Comment by kRHYME7** [comment]
Is this worth complicating things?

Setting more backend is tedious already.

Though we can have a flag something like this.

--filetypes "gif:mp4:"

this filters out other filetypes. As for the backend, It doesn't matter. 


---

I guess this question is more like this?


```toml
[wallpaper]
backend=swww


[wallpaper.swww]
filetypes=[...]

[wallpaper.mpvpaper]
filetypes=[...]
```

Now when each of the filetypes in a backend is declare use it as the input for the wallpaper search?
