### DISCUSSION TITLE
Wallbash Support for k9s.

### DISCUSSION THREAD

**Discussion by RWayne93** [HyDE-Project/HyDE#489] [Ideas]
Been a long time user of this rice now before it became HyDE and was just curious if it would be hard to add wallbash support for something like k9s which supports some theming via yaml files. https://github.com/derailed/k9s

**Comment by kRHYME7** [comment]
Yes. Though I need to learn this tool to effectively use the skin 😅. Can you guide me on what's the minimal structure for this?

**Comment by RWayne93** [comment]
To customize themes in K9s on Arch Linux, you only need the YAML files for themes stored in the `.skins` directory. 

On Arch, you can list available themes with:

ls ~/.config/k9s/skins

then you refernce them as skin: skin in the config.yaml

```bash
k9s:
  liveViewAutoRefresh: false
  screenDumpDir: /home/archie/.local/state/k9s/screen-dumps
  refreshRate: 2
  maxConnRetry: 5
  readOnly: false
  noExitOnCtrlC: false
  ui:
    enableMouse: false
    headless: false
    logoless: false
    crumbsless: false
    reactive: false
    noIcons: false
    defaultsToFullScreen: false
    skin: skin  # Replace 'skin' with the name of your theme file (without .yaml extension)
  skipLatestRevCheck: false
  disablePodCounting: false
  shellPod:
    image: busybox:1.35.0
    namespace: default
    limits:
      cpu: 100m
      memory: 100Mi
  imageScans:
    enable: false
    exclusions:
      namespaces: []
      labels: {}
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: -1
    textWrap: false
    showTime: false
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70

**Reply by kRHYME7** [reply]
Do we need commands to activate it? like external commands?

**Reply by RWayne93** [reply]
no seems like the theme will just be applied on startup if it is there in the config.yaml

**Reply by kRHYME7** [reply]
No hot reload of themes? Though it should be simple!

**Reply by RWayne93** [reply]
i don't think so after going through the readme on the k9s github it looks like you have to change the theme it references in the config.yaml save and exit then relaunch k9s in the terminal.

**Reply by kRHYME7** [reply]
Hot reload is not really that important so it should be fine. Will look into this tomorrow.

**Reply by kRHYME7** [reply]
@RWayne93  

add this to  `~/.config/hyde/wallbash/always/k9s.dcol` then run ` hydectl reload `  > relaunch k9s
```yaml
${XDG_CONFIG_HOME:-$HOME/.config}/k9s/skins/wallbash.yaml
# Wallbash skin by HyDE-Project!
k9s:
  # General K9s styles
  body:
    fgColor: "<wallbash_txt1>" # Foreground
    bgColor: "<wallbash_pry1>" # Background
    logoColor: "<wallbash_1ax3>" # Logo
  # ClusterInfoView styles.
  info:
    fgColor: "<wallbash_txt1>" # Foreground
    sectionColor: "<wallbash_1ax2>" # Section headers
  # Help panel styles
  help:
    fgColor: "<wallbash_txt1>" # Foreground
    bgColor: "<wallbash_pry1>" # Background
    keyColor: "<wallbash_1ax4>" # Key bindings
    numKeyColor: "<wallbash_1ax5>" # Numeric keys
    sectionColor: "<wallbash_1ax2>" # Section headers
  frame:
    # Borders styles.
    border:
      fgColor: "<wallbash_pry3>" # Border
      focusColor: "<wallbash_1ax2>" # Focused border
    # MenuView attributes and styles.
    menu:
      fgColor: "<wallbash_txt1>" # Foreground
      # Style of menu text. Supported options are "dim" (default), "normal", and "bold"
      fgStyle: normal
      keyColor: "<wallbash_1ax4>" # Key bindings
      # Used for favorite namespaces
      numKeyColor: "<wallbash_1ax5>" # Numeric keys
    # CrumbView attributes for history navigation.
    crumbs:
      fgColor: "<wallbash_txt1>" # Foreground
      bgColor: "<wallbash_pry4>" # Slightly lighter background
      activeColor: "<wallbash_pry3>" # Active crumb
    # Resource status and update styles
    status:
      newColor: "<wallbash_1ax3>" # New items
      modifyColor: "<wallbash_1ax2>" # Modified items
      addColor: "<wallbash_1ax4>" # Added items
      errorColor: "<wallbash_pry3>" # Error state
      highlightcolor: "<wallbash_1ax5>" # Highlighted items
      killColor: "<wallbash_pry3>" # Kill status
      completedColor: "<wallbash_2ax7>" # Completed items
    # Border title styles.
    title:
      fgColor: "<wallbash_1ax2>" # Title text
      bgColor: "<wallbash_pry1>" # Title background
      highlightColor: "<wallbash_pry3>" # Highlighted title
      counterColor: "<wallbash_1ax5>" # Counter
      filterColor: "<wallbash_1ax4>" # Filter indicator
  views:
    # TableView attributes.
    table:
      fgColor: "<wallbash_txt1>" # Table text
      bgColor: "<wallbash_pry1>" # Table background
      cursorColor: "<wallbash_1ax2>" # Cursor
      # Header row styles.
      header:
        fgColor: "<wallbash_pry3>" # Header text
        bgColor: "<wallbash_pry4>" # Header background
        sorterColor: "<wallbash_1ax2>" # Sort indicator
    # YAML info styles.
    yaml:
      keyColor: "<wallbash_pry3>" # YAML keys
      colonColor: "<wallbash_txt1>" # Colon separator
      valueColor: "<wallbash_1ax3>" # YAML values
    # Logs styles.
    logs:
      fgColor: "<wallbash_txt1>" # Log text
      bgColor: "<wallbash_pry1>" # Log background
      indicator:
        fgColor: "<wallbash_1ax2>" # Log indicator
        bgColor: "<wallbash_pry1>" # Indicator background
        toggleOnColor: "<wallbash_1ax3>" # Toggle on
        toggleOffColor: "<wallbash_2ax7>" # Toggle off
```
