### DISCUSSION TITLE
How to set a live wallpaper [mp4, mkv]

### DISCUSSION THREAD

**Discussion by red-m0narch** [HyDE-Project/HyDE#667] [Q&A]
How can I set wallpaper to mp4 file format, it goes undetected. 
I could convert to gif but it would be a hassle.
![image](https://github.com/user-attachments/assets/d293504a-704b-4b83-ad3c-6e6d6a0b7300)

**Comment by kRHYME7** [comment]
```toml
[wallpaper]
    backend = "mpvpaper" # Should be installed 
    custom_paths = [
        "$XDG_VIDEOS_DIR/Wallpapers",
    ] # List of paths to search for wallpapers
    filetypes = [ "mp4", "mkv" ] # explicit file types
```
