### DISCUSSION TITLE
Installation / updater / uninstallation manager

### DISCUSSION THREAD

**Discussion by rasputyashka** [HyDE-Project/HyDE#899] [Ideas]
I'm currently working on the installation TUI for HyDE, and I'd like to know if anyone has any feature requests or suggestions at this point.

![image](https://github.com/user-attachments/assets/84b96813-3603-4f4f-bb06-6965107d5bca)

This is what it looks like right now.

I'm currently thinking about how to handle option management. Should we have a dedicated configuration file that defines all available options, which the app reads when generating the menu? Should this config be manually written or generated via a script?

I'm considering introducing an abstraction layer between the config and the app — for example, a Python-based script that defines all options as Python objects and then outputs .toml or .yml files automatically.

Currently, the app supports:

    Yes/No options,

    "One of many" options,

    "Several of many" options.

What other types of options might be useful?

I think that we should also define interface for a  script that will be called when user clicks install/update/uninstall button, are we ok with current install.sh scripts or do we want to change them in the future?

**Comment by rasputyashka** [comment]
As for config file, I do not like using json as a configuration files because it's possible to use comments in here, so I would like to avoid them.

I am thinking of a toml or a yaml, but it feels like yaml should be more appropriate here (it's easier to write and read a list of objects, IMO toml is good as a single configuration point of several applications or pieces, not as a way of describing something)

My proposed strucure is as follows:

```yml
options:
  - name: foo
    type: boolean
    default: false
    description: "foo description"

  - name: bar
    type: one_of
    default:
      - default1
      - default2
    possible_values:
      - default1
      - default2
      - default3
    description: "bar description"
```
