### ISSUE TITLE
Interface: option to change swww transition 

### ISSUE THREAD

**Issue by kRHYME7** [HyDE-Project/HyDE#16]
from https://github.com/prasanthrangan/hyprdots/issues/2040 

Add a new variable in hyderc.

**Comment by kRHYME7** [comment]
using toml will be better 

```toml
[swww]
transition=grow

```
