### ISSUE TITLE
How do change icon size in rofi

### ISSUE THREAD

**Issue by elit3rjmg** [HyDE-Project/HyDE#353]
![Image](https://github.com/user-attachments/assets/6f30c7dd-8704-4f40-9486-d53e07e86dc9)

**Comment by kRHYME7** [comment]
What style is this ? See `~/.local/share/rofi/themes/` and copy a file from there and modify it.  Also read how the rofi manpage/wiki/docs




After modifying, remember the filename. 
Now edit `~/.config/hyde/config.toml` and add this lines 
```toml
[rofi.launcher]
style="your_style" # this is this the style
scale = 12 # for scaling
```
