### ISSUE TITLE
[Bug]: starship doesn't show python virtualenv

### ISSUE THREAD

**Issue by amirreza8002** [HyDE-Project/HyDE#551]
### Description

hi
so the starship configs that come with Hyde have a section for python
but it doesn't include python virtualenvs (starship's default config has it)

so it gets confusing when doing python development

### Steps to Reproduce

make a python venv `python -m venv .venv`
activate it `source .venv/bin/activate`

### Expected Behavior

show something like `(package name)` in the prompt 

### Actual Behavior

no `(package name)`

### Environment

zsh
oh my zsh
starship

**Comment by kRHYME7** [comment]
@prime-run

**Comment by prime-run** [comment]
@amirreza8002 add `${virtualenv}` to `~/.config/starship/starship.toml :134`

something like:
```toml
[python]
format = "[${symbol}(env::${virtualenv})]($style)"
style = "bold bright-yellow"
symbol = "[ ](bold bright-blue)"
version_format = "${raw}"

```
