### ISSUE TITLE
nwg-look - Icons Don't Change

### ISSUE THREAD

**Issue by 0pLuS0** [HyDE-Project/HyDE#779]
Hi,

I posted an issue upstream;

https://github.com/nwg-piotr/nwg-look/issues/98

Because I'm not sure if it's a problem with nwg-look, or something hardcoded maybe in HyDE causing it to not change icons?

THANKS

**Comment by kRHYME7** [comment]
can you `ls ~/dconf ` ? This should not exist.


Does changing themes change your icon?

**Comment by kRHYME7** [comment]
JuSt like nwg look our wallpaper/theme switcher writes to the files that nwg does write too.

**Comment by 0pLuS0** [comment]
I have these /paths for dconf;
~/.cache/dconf/
~/.config/dconf/

No, changing themes doesn't change the icons.

HyDE's wallpaper/theme switcher only changes wallpapers and themes, not icons?

THANKS

**Comment by 0pLuS0** [comment]
While we're on the subject of themes, is HyDE using/doing anything with Kvantum?

I noticed the Kvantum Manager in the menu, but being new with Hyprland, it's not like you can theme all QT apps like you would under KDE. Like Dolphin looks more like a Hyprland/Wayland UI.

THANKS

**Comment by kRHYME7** [comment]
Some themes have icons what theme are you transitioning to and from?

**Comment by 0pLuS0** [comment]
I wasn't trying to change the theme, just the icons.

The default in HyDE is Tela Circle Dracula.

THANKS

**Comment by kRHYME7** [comment]
> While we're on the subject of themes, is HyDE using/doing anything with Kvantum?

yes it is generated as `wallbash`.

**Comment by kRHYME7** [comment]
Please provide outputs for this

```sh
cat $XDG_RUNTIME_DIR/hyde/environment
 ```


Also try to replicate  this and give me the output 

![Image](https://github.com/user-attachments/assets/a8b6c668-f455-4ab3-b8ed-b3621c8c9bf7)

**Comment by 0pLuS0** [comment]
Hi @kRHYME7 

It looks like themes/icons are hardcoded to one another. I finally noticed when I changed the theme, the animated wallpaper that has the girl on the broom, and the cat in the window, the icons also change to the Pink.

I'm just use to using Slackware, and doing everything by hand, and when I simply picked an iconset to use with the default theme, when you first start HyDE, the icons wouldn't change, that's all.

```
cat $XDG_RUNTIME_DIR/hyde/environment

_SHELL='/usr/bin/zsh'
GDK_BACKEND='wayland,x11,*'
QT_QPA_PLATFORM='wayland;xcb'
SDL_VIDEODRIVER='wayland'
CLUTTER_BACKEND='wayland'
XDG_CURRENT_DESKTOP='Hyprland'
XDG_SESSION_TYPE='wayland'
XDG_SESSION_DESKTOP='Hyprland'
QT_AUTO_SCREEN_SCALE_FACTOR='1'
QT_WAYLAND_DISABLE_WINDOWDECORATION='1'
QT_QPA_PLATFORMTHEME='qt6ct'
HYDE_PATH='/home/foo/.local/bin:/home/foo/.local/lib/hyde::/home/foo/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl'
MOZ_ENABLE_WAYLAND='1'
GDK_SCALE='1'
ELECTRON_OZONE_PLATFORM_HINT='auto'
XDG_RUNTIME_DIR='/run/user/1000'
XDG_CONFIG_HOME='/home/foo/.config'
XDG_CACHE_HOME='/home/foo/.cache'
XDG_DATA_HOME='/home/foo/.local/share'
_GTK_THEME='Catppuccin-Mocha'
_ICON_THEME='Tela-circle-dracula'
_COLOR_SCHEME='prefer-dark'
_CURSOR_SIZE='24'
_CURSOR_THEME='Bibata-Modern-Ice'
FONT='Cantarell'
FONT_SIZE='10'
DOCUMENT_FONT='Cantarell'
DOCUMENT_FONT_SIZE='10'
MONOSPACE_FONT='CaskaydiaCove Nerd Font Mono'
MONOSPACE_FONT_SIZE='9'
FONT_ANTIALIASING='rgba'
FONT_HINTING='full'
HYDE_RUNTIME_DIR='/run/user/1000/hyde'
HYDE_CONFIG_HOME='/home/foo/.config/hyde'
HYDE_CACHE_HOME='/home/foo/.cache/hyde'
HYDE_DATA_HOME='/home/foo/.local/share/hyde'
HYDE_STATE_HOME='/home/foo/.local/state/hyde'
export TERMINAL='/usr/bin/kitty'
export LOCKSCREEN='hyprlock'%              
```
```
gsettings get org.gnome.desktop.interface icon-theme
'Tela-circle-dracula'

 gsettings set org.gnome.desktop.interface icon-theme default
gsettings get org.gnome.desktop.interface icon-theme
'default'
```

THANKS

**Comment by kRHYME7** [comment]
hmmm you probably need to look into this. 
It looks like there' nothing wrong with it. Nwg-look config will be overwritten on theme /wallpaper changes as nwg-look only concerns GTK, therefore  we have a wrapper script for that. 



https://hydeproject.pages.dev/en/configuring/config_toml/


https://hydeproject.pages.dev/en/configuring/config_toml/#hyprland

---
would you like to have a gloabl icon-theme even on theme changes ?

**Comment by 0pLuS0** [comment]
Not sure what you mean about a global icon-theme...

All I know is that I've never used a Distro, along with all the various DE/WM out there, where you couldn't simply change a theme, and then choose any icons to go with it.

I've never seen before till now where themes and icons are combined, and the only way to change the icons, is by changing the theme set.

Maybe I'm to old school, and didn't realize they were being combined as all in one now. I do know all the major distros with KDE, Gnome, Cinnamon, Xfce, etc, themes are themes, and icons are icons, and you can mix and match.

It sure would be nice if we could mix and match them by hand too in HyDE.

Thanks

**Comment by kRHYME7** [comment]
> I've never seen before till now where themes and icons are combined, and the only way to change the icons, is by changing the theme set.

We ought to have consistent themes. If user wants to have custom then it is simple, copy the theme and make it your own. 

> It sure would be nice if we could mix and match them by hand too in HyDE.

Have you checked the provided links? 

https://hydeproject.pages.dev/en/configuring/config_toml/#hyprland

---

>  I do know all the major distros with KDE, Gnome, Cinnamon, Xfce, etc, themes are themes, and icons are icons, and you can mix and match.

Also, HyDE is no DE these are only Dot files combined to be usable. 

Your  mentioned  DE all have their own ecosystem. So they can mix&match their  GUI as it is simply a single entry point for configuration like GTK  or QT like kdeglobals,gsettings whatever. 

HyDE is only modifying those entry points to have an at least consistent look.  HyDE modifies QT,GTK and other niche configuration, that is why it is wrap as a whole. 

> It sure would be nice if we could mix and match them by hand too in HyDE.


in `~/.config/hyde/config.toml` 
```toml
# Hyprland configuration.
[hyprland]
browser = "firefox"  # Browser.
editor = "code"  # Editor.
explorer = "dolphin"  # File manager.
idle = "hypridle"  # Idle manager.
lockscreen = "lockscreen.sh"  # Lockscreen.
terminal = "kitty"  # Terminal.
quickapps = "kitty"  # Quick apps.
bar = "waybar"  # Bar.
color_scheme = "prefer-dark"  # Color scheme.
gtk_theme = "Wallbash-Gtk"  # GTK theme.
icon_theme = "Tela-circle-dracula"  # Icon theme.
cursor_size = 24  # Cursor size.
cursor_theme = "Bibata-Modern-Ice"  # Cursor theme.
button_layout = ""  # Button layout. (gtk only)
document_font_size = 10  # Document font size.
font = "Canterell"  # Font.
font_antialiasing = "rgba"  # Font antialiasing.
font_hinting = "full"  # Font hinting.
font_size = 10  # Font size.
monospace_font = "CaskaydiaCove Nerd Font Mono"  # Monospace font.
monospace_font_size = 9  # Monospace font size.
background_path = ""  # LockScreen's Background path.
```


--- 



For your custom stuff bundle as your own you can make it a theme! 


See `ls ~/.config/hyde/themes/ `

Choose base you want. 

`cp' $HOME/.config/hyde/themes/Catppuccin Mocha"   $HOME/.config/hyde/themes/CustomTheme` 

  then modify the `hypr.theme` 

See this for further context https://hydeproject.pages.dev/en/theming/making-themes/
